### ISSUE TITLE
hisat2_extract_splice_sites.py: command not found

### ISSUE THREAD

**Issue by bshrestha0** [wenzelm/slidr-sloppr#5]
Hi, 

I am trying to run example_data.sh as a test run but it failed during the splice site extraction step. Lines 413 and 414 in the script slider.sh is looking for two python scripts "hisat2_extract_splice_sites.py"  and "hisat2_extract_exons.py" but I don't see those two scripts in the repository. Wondering if I am missing something here?

Also the line 352 in slider.sh, "load_dependencies", should be commented, otherwise I assume it will throw an error.

Please let me know when you have a moment.

**Comment by wenzelm** [comment]
Hi Bikash,

These two Python scripts are part of HISAT2. The fact that SLIDR can't find the scripts suggests that you haven't got HISAT2 in your PATH environmental variable. You'll need to add the necessary commands to the load_dependencies function (module load or export PATH).

You can customise the load_dependencies function in any way that is required for your system. If you don't need it at all, comment out all content of that function.

Best wishes,
Marius

**Comment by bshrestha0** [comment]
Hi Marius, 

Thanks for your quick response. I thought those two scripts are custom scripts. Installing hisat2 resolves the issue.

Yes, I agree I can comment out the load_dependencies function at the beginning of the script but I was referring to the line 352, which will be considered as a bash command if you don't comment that specific line. 

In any case, after installing hisat2, example_data.sh ran successfully. 

Best regards,
Bikash

**Comment by wenzelm** [comment]
Glad to hear it works now :)
If you leave the function definition but remove all function content you won't have to comment out line 352. Conversely, it's also fine if you comment it out. Either option will work.
Hope you find some nice SLs!
